// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHHWLVN93CiypWuGXz6t74TnKMRcdpEtg',
    appId: '1:617705387285:web:817d0147eef66461c9a51c',
    messagingSenderId: '617705387285',
    projectId: 'services-c0beb',
    authDomain: 'services-c0beb.firebaseapp.com',
    storageBucket: 'services-c0beb.firebasestorage.app',
    measurementId: 'G-H599RD09P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4sGAs5IxyJO9RZebzDpnmWfdR4T9vzc',
    appId: '1:617705387285:android:aef471188e55abaac9a51c',
    messagingSenderId: '617705387285',
    projectId: 'services-c0beb',
    storageBucket: 'services-c0beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpHTPyeYQAWYiGcJM4ht2JN3AzSMk3GY',
    appId: '1:617705387285:ios:dce2eb939725ac7cc9a51c',
    messagingSenderId: '617705387285',
    projectId: 'services-c0beb',
    storageBucket: 'services-c0beb.firebasestorage.app',
    iosBundleId: 'com.example.servicesNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpHTPyeYQAWYiGcJM4ht2JN3AzSMk3GY',
    appId: '1:617705387285:ios:dce2eb939725ac7cc9a51c',
    messagingSenderId: '617705387285',
    projectId: 'services-c0beb',
    storageBucket: 'services-c0beb.firebasestorage.app',
    iosBundleId: 'com.example.servicesNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHHWLVN93CiypWuGXz6t74TnKMRcdpEtg',
    appId: '1:617705387285:web:5aa118866421aa69c9a51c',
    messagingSenderId: '617705387285',
    projectId: 'services-c0beb',
    authDomain: 'services-c0beb.firebaseapp.com',
    storageBucket: 'services-c0beb.firebasestorage.app',
    measurementId: 'G-Y53MG96KXS',
  );

}